on:
  push:
    branches:
      - master1





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'folder content Berfore checkout'
        run: ls

      - uses: actions/checkout@v3

      - name: 'printing folder content after checkout'
        run: ls