on:
  push:
    branches:
      - master1





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 'login to docker hup'
        run: docker login --username omar790 --password dckr_pat_DfzndQZWuo9SdckhSfnmS-21i5I